"""Generate a sandboxed Python script that runs a validated ProjectPlan
inside Houdini's ``hython`` interpreter.

The LLM never produces Python directly. This module turns a validated
:class:`ProjectPlan` into a static script whose plan data is embedded as
a JSON literal and dispatched through a fixed handler table. Action
types not in :data:`SUPPORTED_ACTION_TYPES` are rejected at build time.
"""

from __future__ import annotations

import inspect as _stdlib_inspect
import json
from typing import Final

from app.houdini import inspector as _inspector_module
from app.houdini.schemas import ProjectPlan

# Sentinels delimit the result payload in the subprocess stdout so we can
# tolerate Houdini's startup chatter without misparsing it.
RESULT_BEGIN: Final[str] = "##PROJECTDEV_RESULT_BEGIN##"
RESULT_END: Final[str] = "##PROJECTDEV_RESULT_END##"

SUPPORTED_ACTION_TYPES: Final[frozenset[str]] = frozenset(
    {
        "create_node",
        "set_parameter",
        "connect_nodes",
        "layout_children",
        "save_file",
        "inspect_scene",
    }
)


class UnsupportedActionError(ValueError):
    """The plan contains an action type the executor cannot run yet."""


_SCRIPT_TEMPLATE = '''"""Auto-generated by ProjectDev. Do not edit."""
from __future__ import annotations

import json
import sys
import traceback

RESULT_BEGIN = {result_begin!r}
RESULT_END = {result_end!r}

_PLAN = json.loads({plan_literal})


def _emit(payload):
    print(RESULT_BEGIN)
    print(json.dumps(payload))
    print(RESULT_END)


try:
    import hou  # type: ignore
except ImportError as exc:  # pragma: no cover - exercised inside hython
    _emit({{"fatal": "hou import failed: " + str(exc), "results": []}})
    sys.exit(2)


# --- Begin embedded inspector ---------------------------------------------
__INSPECTOR_SOURCE__
# --- End embedded inspector -----------------------------------------------


def _resolve(path):
    node = hou.node(path)
    if node is None:
        raise LookupError("Node not found: " + repr(path))
    return node


def _set_one(node, name, value):
    parm = node.parm(name)
    if parm is not None:
        parm.set(value)
        return
    tup = node.parmTuple(name)
    if tup is not None:
        tup.set(value)
        return
    raise LookupError(
        "Parameter not found on " + repr(node.path()) + ": " + repr(name)
    )


def _create_node(action):
    parent = _resolve(action["context_path"])
    node = parent.createNode(action["node_type"], action["node_name"])
    for key, value in (action.get("parameters") or {{}}).items():
        _set_one(node, key, value)
    return {{"path": node.path()}}


def _set_parameter(action):
    node = _resolve(action["target_path"])
    for key, value in action["parameters"].items():
        _set_one(node, key, value)
    return {{"path": node.path()}}


def _connect_nodes(action):
    src = _resolve(action["from_path"])
    dst = _resolve(action["to_path"])
    dst.setInput(
        int(action.get("to_input", 0)),
        src,
        int(action.get("from_output", 0)),
    )
    return {{"from": src.path(), "to": dst.path()}}


def _layout_children(action):
    parent = _resolve(action["context_path"])
    parent.layoutChildren()
    return {{"path": parent.path()}}


def _save_file(action):
    hou.hipFile.save(action["file_path"])
    return {{"file_path": action["file_path"]}}


def _inspect_scene(action):
    return describe_scene(
        hou,
        context_path=action.get("context_path", "/obj"),
        max_depth=int(action.get("max_depth", 1)),
    )


_HANDLERS = {{
    "create_node": _create_node,
    "set_parameter": _set_parameter,
    "connect_nodes": _connect_nodes,
    "layout_children": _layout_children,
    "save_file": _save_file,
    "inspect_scene": _inspect_scene,
}}


def _run():
    results = []
    for index, action in enumerate(_PLAN.get("actions", [])):
        atype = action.get("action_type")
        handler = _HANDLERS.get(atype)
        if handler is None:
            results.append({{
                "index": index,
                "action_type": atype,
                "success": False,
                "error": "action " + repr(atype) + " not supported by executor",
            }})
            continue
        try:
            data = handler(action)
            results.append({{
                "index": index,
                "action_type": atype,
                "success": True,
                "data": data,
            }})
        except Exception as exc:
            results.append({{
                "index": index,
                "action_type": atype,
                "success": False,
                "error": type(exc).__name__ + ": " + str(exc),
                "traceback": traceback.format_exc(),
            }})
    _emit({{"results": results, "fatal": None}})


if __name__ == "__main__":
    _run()
'''


_INSPECTOR_FUNCTIONS = (
    _inspector_module._is_simple,
    _inspector_module._to_jsonable,
    _inspector_module.collect_node_parameters,
    _inspector_module.collect_inputs,
    _inspector_module.collect_outputs,
    _inspector_module.describe_node,
    _inspector_module.describe_scene,
)


def _inspector_source() -> str:
    header = f"MAX_PARAMETERS_PER_NODE = {_inspector_module.MAX_PARAMETERS_PER_NODE}\n"
    return header + "\n\n".join(
        _stdlib_inspect.getsource(fn) for fn in _INSPECTOR_FUNCTIONS
    )


def build_script(plan: ProjectPlan) -> str:
    """Return a self-contained Python script that runs ``plan`` under hython.

    Raises :class:`UnsupportedActionError` if the plan contains an action
    type the executor does not yet implement.
    """

    _ensure_supported(plan)
    plan_dict = plan.model_dump(mode="json")
    plan_json = json.dumps(plan_dict, sort_keys=True)
    formatted = _SCRIPT_TEMPLATE.format(
        result_begin=RESULT_BEGIN,
        result_end=RESULT_END,
        plan_literal=repr(plan_json),
    )
    return formatted.replace("__INSPECTOR_SOURCE__", _inspector_source())


def _ensure_supported(plan: ProjectPlan) -> None:
    unsupported = sorted(
        {a.action_type for a in plan.actions if a.action_type not in SUPPORTED_ACTION_TYPES}
    )
    if unsupported:
        raise UnsupportedActionError(
            "Executor does not yet support action type(s): "
            + ", ".join(unsupported)
        )


__all__ = [
    "RESULT_BEGIN",
    "RESULT_END",
    "SUPPORTED_ACTION_TYPES",
    "UnsupportedActionError",
    "build_script",
]
